trunk/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from os import path as os_path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sequias/', include('sequias.foo.urls')),
    (r'^', include('sequias.urls')),
    (r'^$', 'sequias.views.index'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

if (settings.DEBUG == True):
    urlpatterns += patterns('',
                            (r'^media/(.*)$', 'django.views.static.serve', {'document_root': os_path.join(settings.MEDIA_ROOT)}),
                        )

trunk/sequias/forms.py
 # -*- coding: UTF-8 -*-

from django import forms
from django.forms import ModelForm
from sequias.models import *
from lugar.models import *

date_inputformats=['%d.%m.%Y','%d/%m/%Y','%Y-%m-%d']

class SequiaForm(forms.Form):
    fecha_inicio = forms.DateField(input_formats=date_inputformats)
    fecha_final = forms.DateField(input_formats=date_inputformats)
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), required=False, empty_label="Todos los Departamentos")
    municipio = forms.CharField(widget = forms.Select, required=False)
    comunidad = forms.CharField(widget = forms.Select, required=False)
    entrevistado = forms.CharField(widget = forms.Select, required=False)
    

trunk/templates/base.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//w3c//DTD XHTML 1.0 Strict//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="shortcut icon" href="/favicon.ico" />
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<title>{% block title %}Sondeo de Sequia{% endblock %}</title>
	<meta http-equiv="Content-Style-Type" content="text/css" />

	<link rel="stylesheet" href="/media/css/style.css" />
	<script type="text/javascript" src="/media/js/jquery.js"></script>
	<script type="text/javascript" src="/media/js/s3Slider.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#slider1').s3Slider({
            timeOut: 4000 
        });
    });
</script>
{% block extraheader %}
{% endblock %}
{% block extra_js %}
{% endblock %}
</head>
<body>

		<div id="header"> <!-- empieza el header -->
		<img src="/media/imagen/gpae31.jpg" width=570 height=78 alt="gpae"/>       
		</div> <!-- termina el header --> 

<div id="page-wrap">  <!-- empieza wrap -->
<hr></hr>
{% block menu %} 
<ul class="nav-menu">
    <li><a href="/">Inicio</a></li>
    <li><a href="/index">Consultar</a></li>
    <li><a href="/admin">Administración</a></li>
</ul>
{% endblock %}
<br>
<hr></hr>
        <div id="main-content"> <!-- empieza main-content -->
            {% block content %}
			<div id="slider1">
				<ul id="slider1Content">
					<li class="slider1Image">
						<a href=""><img src="/media/imagen/frijol.jpg" alt="frijol"/></a>
						<span class="bottom"><strong>El Frijol</strong><br />Es una planta originaria de América que se cultiva en todo el mundo. Existen numerosas variedades y de ellas se consumen tanto las vainas verdes (judía verde o chauchas) como los granos secos.</span></li>
					<li class="slider1Image">
          					<img src="/media/imagen/maiz.jpg" alt="maiz"/>
          					<span class="bottom"><strong>El Maíz</strong><br />Es una gramínea anual originaria de las Américas introducida en Europa en el siglo XVI. Actualmente, es el cereal con mayor volumen de producción en el mundo, superando al trigo y el arroz. En la mayor parte de los países de América, el maíz constituye la base histórica de la alimentación regional y uno de los aspectos centrales de la cultura mesoamericana.</span>
      				</li>
					<li class="slider1Image">
          					<img src="/media/imagen/sorgo1.jpg" alt="sorgo"/>
          					<span class="bottom"><strong>El Sorgo</strong><br />Género botánico de unas 20 especies de gramíneas oriundas de las regiones tropicales y subtropicales de África oriental.Se cultivan en su zona de origen, Europa, América y Asia como cereal para consumo humano, animal, en la producción de forrajes, y para la elaboración de bebidas alcohólicas. Su resistencia a la sequía y el calor lo hace un cultivo importante en regiones áridas, y es uno de los cultivos alimentarios más importantes del mundo.</span></li>
      				<div class="clear slider1Image"></div>
   				</ul>
			</div>
            {% endblock %}
            <div id="footer">
                  <p><a href="http://www.simas.org.ni">SIMAS 2009</a></p>
            </div>
        </div> <!-- termina el main-content -->

</div> <!-- termina wrap -->

</body>

</html>

trunk/templates/index.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//w3c//DTD XHTML 1.0 Strict//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>{% block title %}Sondeo sobre Sequia en Nicaragua{% endblock %}</title>
    <meta http-equiv="Content-Style-Type" content="text/css" />

    <link rel="stylesheet" href="/media/css/style.css" />
    <link rel="stylesheet" href="/media/css/jquery-ui-1.7.2.custom.css" />
    <script type="text/javascript" src="/media/js/jquery.js"></script>
	<script type="text/javascript" src="/media/js/s3Slider.js"></script>
    <script type="text/javascript" src="/media/js/jquery-ui-1.7.2.custom.min.js"></script>

<script>
        $(document).ready(function() {
        $("#id_fecha_inicio").datepicker({ dateFormat: 'yy-mm-dd', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],changeYear: true});
        $("#id_fecha_final").datepicker({ dateFormat: 'yy-mm-dd', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],changeYear: true});
        var departamento = document.getElementById("id_departamento");
        var municipio = document.getElementById("id_municipio");
        var comunidad= document.getElementById("id_comunidad");
        var entrevistado = document.getElementById("id_entrevistado");
        $("#id_departamento").change(function () {
            var index = departamento.options.selectedIndex;
            var id = departamento.options[index].value;
            $.getJSON("/ajax/municipio/" + id +"/",
            function(data){
                municipio.options.length = 0;
                comunidad.options.length = 0;
                municipio.options[0] = new Option("--------");
                for(i=0; i< data.length; i++){
                    municipio.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
        $("#id_municipio").change(function () {
            var index = municipio.options.selectedIndex;
            var id = municipio.options[index].value;
            $.getJSON("/ajax/comunidad/" + id +"/",
            function(data){
                comunidad.options.length = 0;
                comunidad.options[0] = new Option("---------");
                for(i=0; i< data.length; i++){
                    comunidad.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
        $("#id_comunidad").change(function () {
            var index = comunidad.options.selectedIndex;
            var id = comunidad.options[index].value;
            $.getJSON("/ajax/entrevista/" + id +"/",
            function(data){
                entrevistado.options.length = 0;
                entrevistado.options[0] = new Option("---------");
                for(i=0; i< data.length; i++){
                    entrevistado.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
 });
</script>

{% block extraheader %}


{% endblock %}
</head>
<body>
        <div id="header"> <!-- empieza el header -->
		<a href="/"><img src="/media/imagen/gpae3.png" width=570 height=78 alt="gpae"/></a>       
		</div> <!-- termina el header --> 

<div id="page-wrap">  <!-- empieza wrap -->
<hr></hr>
{% block menu %} 
<ul class="nav-menu">
    <li><a href="/index">Consultar</a></li>
    <li><a href="/perdida">Pérdidas</a></li>
    <li><a href="/disponibilidad">Disponibilidad</a></li>
    <li><a href="/nutricion">Nutrición</a></li>
    <li><a href="/descargar/xls">hoja XLS</a></li>
    <li><a href="/descargar/word">Reporte</a></li>
    <li><a href="/admin">Administración</a></li>
</ul>
{% endblock %}
<br>
<hr></hr>
        <div id="main-content"> <!-- empieza main-content -->
<div id="filtros"><b>Filtros</b> :: Departamento: <i>{{ request.session.departamento.nombre }}</i> | Municipio: <i> {{request.session.municipio.nombre}}</i> | Comunidad:<i> {{request.session.comunidad.nombre}}</i> | Entrevistado: <i> {{ request.session.entrevistado.nombre }}</i></div>
    {% block content %}
                    <form action"." method="POST">
                    <fieldset>
                    <div id="formulario_tabla">
                           <div class="form_label"><b>{{form.fecha_inicio.label}}</b></div>
                           <div  class="datepicker">{{form.fecha_inicio}}</div>
                           <div class="form_label"><b>{{form.fecha_final.label}}</b></div>
                           <div class="datepicker">{{form.fecha_final}}</div>
                           <div id="general_form">
                              <div class="form_label"><b>{{form.departamento.label}}</b></div>
                              <div class="form_widget">{{form.departamento}}</div>
                              <div class="form_label"><b>{{form.municipio.label}}</b></div>
                              <div class="form_widget">{{form.municipio}}</div>
                              <div class="form_label"><b>{{form.comunidad.label}}</b></div>
                              <div class="form_widget">{{form.comunidad}}</div>
                              <div class="form_label"><b>{{form.entrevistado.label}}</b></div>
                              <div class="form_widget">{{form.entrevistado}}</div>
                           </div>
                    </div>

                      <input type="submit" value="Consultar" id="boton" class="filtro"/>
                    </fieldset>
                    </form>
{%if mensaje%}
                    <div id="mensaje">{{mensaje}}</div>
{%endif%}
            {% endblock %}
           <div id="footer">
                  <p><a href="http://www.simas.org.ni">SIMAS 2009</a></p>
            </div>
        </div> <!-- termina el main-content -->
 <div id="sidebar"><!-- empieza siderbar-->
{% block siderbar %}

{% endblock %} </div> <!--termina el sideber -->
</div> <!-- termina wrap -->
</body>
</html>